### ISSUE TITLE
[OpenSuSE 15] auto-builder creates bluebanquise RPM with %{dist} in the name

### ISSUE THREAD

**Issue by neilmunday** [bluebanquise/infrastructure#16]
When selecting option 8 for `auto_builder.sh` it generates a BlueBanquise RPM with `%{dist}` in the name:

E.g.

```
/usr/src/packages/RPMS/noarch/ipxe-x86_64-bluebanquise-1.3.0-1%{dist}.noarch.rpm
```

**Comment by neilmunday** [comment]
Note: https://en.opensuse.org/openSUSE:Packaging_for_Leap states that the macro `is_opensuse` is undefined and also states:

> Important Update as of 2021: is_opensuse ideally notbe used only. To distinguish in between openSUSE Tumbleweed and SUSE Linux Enterprise check the presence of sle_version. openSUSE Leap 15.3+ should have the identical functionality as SUSE Linux Enterprise.

**Comment by oxedions** [comment]
Close due to PR that fix this.
