### ISSUE TITLE
FR - Provide source rpms for external packages

### ISSUE THREAD

**Issue by thiagocardozo** [bluebanquise/infrastructure#20]
The repo at http://bluebanquise.com/repository/releases/1.5-dev/ currently only has the rpms.
Could we also get the src.rpms?

**Comment by oxedions** [comment]
Ok for me, I will try to add this.

**Comment by oxedions** [comment]
The Pi worked all the night for you.
http://bluebanquise.com/repository/releases/1.5-dev/el8/sources/
Done ;-)
